spring.application.name=lynkr-backend
# Application Server Port Binding
server.port=${PORT:8080}

# Datasource Configuration for Render PostgreSQL
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://dpg-d9u20cv40ujc73fc5d4g-a:5432/lynkr_db?sslmode=require}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:lynkr_db_user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:vK4aJNnnoDLXcp9dP66cBEB0Y55cyV3L}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Auto-Schema Creation
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Hikari Connection Pool Fail-fast Prevention
spring.datasource.hikari.initialization-fail-timeout=-1
spring.datasource.hikari.maximum-pool-size=5

# Lynkr Custom Application Config
lynkr.app.base-url=https://lynkr-backend-3kal.onrender.com
lynkr.jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
lynkr.jwt.expiration-ms=86400000
