spring.application.name=lynkr-backend

# Web Server Port
server.port=${PORT:8080}

# PostgreSQL Datasource Configuration
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://dpg-d9u20cv40ujc73fc5d4g-a:5432/lynkr_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:lynkr_db_user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:vK4aJNnnoDLXcp9dP66cBEB0Y55cyV3L}
spring.datasource.driver-class-name=org.postgresql.Driver

# Prevent Startup Crash on DB Delay
spring.datasource.hikari.initialization-fail-timeout=-1
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.maximum-pool-size=5

# JPA / Hibernate Auto-Table Creation
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults=false

# Lynkr Custom Application Config
lynkr.app.base-url=https://lynkr-backend-3kal.onrender.com
lynkr.jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
lynkr.jwt.expiration-ms=86400000
